name: ZAP Scan

on:
  push:
    branches: [ main ]

jobs:
  zap-scan:
    runs-on: ubuntu-latest
    services:
      juice-shop:
        image: bkimminich/juice-shop
        ports:
          - 3000:3000

    steps:
      - name: Run ZAP Baseline Scan
        run: |
          docker run --rm -t owasp/zap2docker-stable zap-baseline.py -t http://juice-shop:3000



