name: ZAP Scan

on:
  push:
    branches: [ main ]

jobs:
  zap-scan:
    runs-on: ubuntu-latest
    services:
      juice-shop:
        image: bkimminich/juice-shop
        ports:
          - 3000:3000

    steps:
      - name: Run ZAP Full Scan
        run: |
          docker run --rm -t \
            -v ${{ github.workspace }}:/zap/wrk \
            zaproxy/zap-stable zap-full-scan.py \
            -t http://juice-shop:3000 -r zap-report.html

      - name: Upload ZAP Report
        uses: actions/upload-artifact@v4
        with:
          name: zap-report
          path: zap-report.html